#!/bin/bash
#
echo -n "Sisesta suvaline täisarv: "
read t_arv
#
arv=0
summa=0
#
while [ $t_arv -gt 0 -o $t_arv -lt 0 ]
do
	arv=$(( $t_arv % 10 ))
	t_arv=$(( $t_arv / 10 ))
	summa=$(( $summa + $arv ))
done
echo "Sisestatud arvu numbrite summa on: $summa"
