#! /bin/bash
#
# kuupäeva ja aja skript
#
date +"Today is %A, %B %m. %Y" # Väljastab kuupäeva
date +"Time is %R" # Väljastab praeguse aja
echo "Calendar of January 2015" # väljastab kalendri pealkirja
cal # Väljastab kalendri
