#! /bin/bash
#
# tervitusskript
#
# skripti algus
#
# echo "Tere User!"
echo -n "Tere " # väljasta ilma reavahetuseta Tere,
echo -n `who am i | cut -c1 | tr [:lower:] [:upper:]` # lõika esimene täht ja muuda suureks
echo -n `who am i | cut -c2-` # löika kõik tähed alates 2-st
echo "!"
#
# skripti lõpp
